CNTL_FRAME_VERSION_SPD3 = 0x8003
CNTL_FRAME_VERSION_ALX1 = 0x80A1

CNTL_FRAME_TYPE_SYN_STREAM = 1
CNTL_FRAME_TYPE_SYN_REPLY = 2
CNTL_FRAME_TYPE_RST_STREAM = 3
CNTL_FRAME_TYPE_PING = 6

CNTL_FRAME_TYPE_STATS_REQ = 0xA1
CNTL_FRAME_TYPE_STATS_REP = 0xA2

CNTL_FRAME_TYPE_CSR = 0xC1
CNTL_FRAME_TYPE_CERT_QUERY = 0xC2
CNTL_FRAME_TYPE_CERT = 0xC3

RST_STREAM_STS_PROTOCOL_ERROR = 1
RST_STREAM_STS_REFUSED_STREAM = 3
RST_STREAM_STS_INTERNAL_ERROR = 6
RST_STREAM_STS_STREAM_ALREADY_CLOSED = 9

ALX1_FLAG_CSR_NOT_FOUND = 0x80

SPDY_FLAG_FIN = 0x01

SPDY_HEADER_SIZE = 8
